### ISSUE TITLE
Remanga failed to fetch data

### ISSUE THREAD

**Issue by ilyasemenow90** [XITRIX/ReManga-iOS#7]
Hi!
Looks like remanga has been updated the API response and app app fails to parse it (home page has an error message).
Failed response is: `let url = "https://api.remanga.org/api/search/catalog/?count=30&ordering=-\(sorting.id)&page=\(page)\(tags)"` It failed by parsing JSON because `msg` is missing.
I resolved the issue (but I couldn't push branch in your repo, so I've created a fork and push changes there).
https://github.com/ilyasemenow90/ReManga-iOS/commit/0fe5bf514616d93505d655621f4ee63b10f306ad

**Comment by XITRIX** [comment]
Hi! You can make pull request, I'll gladly merge it

**Comment by ilyasemenow90** [comment]
@XITRIX Thanks, here is a PR: https://github.com/XITRIX/ReManga-iOS/pull/8
